const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');

console.log('HOMEPAGE VISUAL CONTRACT...');

const styles = read('styles.css');
const index = read('index.html');
const archive = read('archive.html');
const insights = read('insights.html');
const stars = read('stars-v2.js');
const siteInit = read('site-init.js');

assert.ok(index.includes('ENGINEERED_SIGNALS'), 'Visual Success section uses operational signal language');
assert.ok(index.includes('Visual Success <span class="visual-success-accent">Systems</span>'), 'Visual Success section uses the restored Systems heading');
assert.ok(index.includes('Quote-First Project Intake'), 'Visual Success section includes quote-first intake card');
assert.ok(index.includes('Fast-Lane Asset Path'), 'Visual Success section includes fast-lane card');
assert.ok(index.includes('Private Delivery Workspace'), 'Visual Success section includes portal delivery card');
assert.ok(!index.includes('ENGINEERED_STATISTICS'), 'reverted statistics eyebrow must not return');
assert.ok(!index.includes('Viewer Engagement Growth'), 'unverified engagement-growth claim must not return');
assert.ok(!index.includes('Visions Delivered Globally'), 'unverified delivered-globally claim must not return');
const studioSection = (index.match(/<section id="about"[\s\S]*?<\/section>/) || [''])[0];
assert.ok(studioSection.includes('founded by ELI3GANT.'), 'identity card leads with ELI3GANT only');
assert.ok(!studioSection.includes('Elijah Huertas'), 'visible identity card must not show legal first and last name');

assert.ok(styles.includes('Clean homepage visual restore'), 'homepage visual restore guard is documented');
assert.ok(styles.includes('html[data-stars="mounted"] .home-page .hero::before'), 'mounted star canvas disables fallback pseudo layer');
assert.ok(styles.includes('html:not([data-stars="mounted"]):not([data-stars="disabled"]) .home-page .hero::before'), 'fallback star layer only renders when canvas is not mounted');
assert.ok(styles.includes('Visual Success Systems restore'), 'restored Visual Success card styling is documented');
assert.ok(!styles.includes('animation: holoFlow'), 'identity card light-mode treatment must not run perpetual shimmer animation');
assert.ok(!styles.includes('mix-blend-mode: color-burn'), 'identity card light-mode treatment avoids expensive color-burn blending');
assert.ok(!styles.includes('background-size: 150px 150px, 230px 230px, 310px 310px'), 'old tiled star fallback must not return');
assert.ok(!styles.includes('otp-static-star-drift'), 'old animated tiled fallback must not return');
assert.ok(styles.includes('opacity: 0.92 !important'), 'dark canvas stars remain visible');
assert.ok(styles.includes('opacity: 0.46 !important'), 'day/light canvas stars remain visible');
assert.ok(styles.includes('html.stars-performance-mode .bg-grain'), 'performance mode pauses grain overlays');
assert.ok(styles.includes('html.stars-performance-mode .home-page .glass-manifesto'), 'performance mode lightens identity card compositor work');
assert.ok(styles.includes('backdrop-filter: blur(10px) saturate(1.05) !important'), 'performance mode keeps premium-lite identity card backdrop blur');
assert.ok(styles.includes('glass-manifesto .sticker-base'), 'performance mode lightens identity card inner glass emblem');
assert.ok(styles.includes('html.stars-performance-mode .home-page .hero .hero-eye-3d'), 'performance mode lightens hero logo compositor work');
assert.ok(styles.includes('html.stars-performance-mode .home-page .hero .hero-logo-wrap::before'), 'performance mode softens hero aura without flattening it');
assert.ok(styles.includes('otp-static-performance-logo'), 'performance mode static logo style is present');
assert.ok(styles.includes('Mobile hero title fit: keep ONLY TRUE / PERSPECTIVE complete on narrow screens.'), 'mobile hero title fit guard is documented');
assert.ok(styles.includes('Mobile hero title fit + spacing/scroll polish') && styles.includes('@media (max-width: 480px)') && styles.includes('@media (max-width: 390px)'), 'mobile hero has late <=480px and <=390px overflow guards');
assert.ok(styles.includes('@media (max-width: 480px)') && styles.includes('@media (max-width: 390px)'), 'mobile hero uses narrow-width media guards');
assert.ok(styles.includes('.home-page .luxe-title .title:last-child') && styles.includes('font-size: min(1.68rem, 7.1vw)'), 'PERSPECTIVE line uses viewport-capped min() sizing');
assert.ok(styles.includes('width: min(100%, calc(100vw - 32px)) !important;'), 'mobile hero title lines use 32px viewport side gutter');
assert.ok(styles.includes('overflow-x: clip'), 'mobile hero blocks horizontal overflow');
assert.ok(styles.includes('Mobile hero title fit + spacing/scroll polish'), 'mobile hero spacing and scroll polish guard is documented');
assert.ok(styles.includes('width: clamp(132px, 36vw, 152px)'), 'mobile hero logo has explicit larger sizing');
assert.ok(styles.includes('height: 100svh !important'), 'mobile star canvas uses safe viewport height');
assert.ok(styles.includes('min-height: auto !important'), 'mobile hero avoids rigid viewport min-height jumps');
assert.ok(styles.includes('position: fixed !important') && styles.includes('max-height: 100dvh !important'), 'mobile star canvas stays fixed without layout height');
assert.ok(styles.includes('inset: -22% !important'), 'mobile hero aura is tightened relative to logo');
assert.ok(styles.includes('max-width: min(100%, calc(100vw - 36px)) !important;'), 'tablet hero title stays inside viewport side padding');
assert.ok(!styles.includes('font-size: clamp(2.05rem, 9.6vw, 3.05rem) !important;'), 'removed oversized mobile PERSPECTIVE clamp that caused clipping');
assert.ok(styles.includes('Premium day-mode services polish: richer depth without changing dark mode.'), 'day-mode services polish guard is documented');
assert.ok(styles.includes('[data-theme="light"] .home-page #services.section-alt'), 'light-mode services section gets its own premium surface');
assert.ok(styles.includes('[data-theme="light"] .home-page #services .service-item'), 'light-mode service cards get scoped contrast treatment');
assert.ok(styles.includes('[data-theme="light"] .home-page #cursor-canvas.stars-mounted'), 'light-mode star canvas remains visible');
assert.ok(styles.includes('.spectral-v-sync .network-pkg h4'), 'mobile spectral variants cannot force package headings past the viewport');
assert.ok(styles.includes('overflow-wrap: anywhere !important'), 'mobile spectral headings wrap safely');

assert.ok(stars.includes("setAttribute('data-stars', 'mounted')"), 'starfield marks canvas-mounted state');
assert.ok(stars.includes("setAttribute('data-stars', 'fallback')"), 'starfield marks safe fallback when canvas init fails');
assert.ok(index.includes('hero-eye-3d') && index.includes('data-hero-animated-src="assets/otp-hero-centered.gif"'), 'homepage hero uses poster-first centered animated gif strategy');
assert.ok(index.includes('hero-eye-poster'), 'homepage hero exposes poster layer for LCP');
assert.ok(index.includes('hero-eye-animated'), 'homepage hero exposes animated gif layer');
assert.ok(styles.includes('--hero-poster-offset-x') && styles.includes('--hero-animated-offset-x'), 'hero layers include small composition offset variables');
assert.ok(styles.includes('hero-eye-animated') && styles.includes('object-position: calc(50% + var(--hero-animated-offset-x))'), 'animated hero layer uses centered object-position compensation');
assert.ok(styles.includes('hero-eye-poster') && styles.includes('object-position: calc(50% + var(--hero-poster-offset-x))'), 'poster hero layer uses centered object-position compensation');
assert.ok(!styles.includes('[data-theme="light"] .home-page .hero-logo-wrap::after {\n  border-color: rgba(0, 0, 0, 0.08);\n  background: rgba(255, 255, 255, 0.32);'), 'light-mode hero ring no longer uses filled pale orb background');
assert.ok(!/hero-logo-wrap[\s\S]{0,420}opacity:\s*1\s*!important/.test(index), 'homepage hero avoids inline opacity overrides that block crossfade');
assert.ok(index.includes('assets/otp-hero-poster.png'), 'homepage hero poster uses dedicated centered png');
assert.ok(index.includes('preload" href="assets/otp-hero-poster.png"'), 'homepage preloads hero poster not full gif');
assert.ok(!index.includes('preload" href="assets/otp-hero-centered.gif"'), 'homepage does not preload full hero gif');
assert.ok(siteInit.includes('activateHeroAnimatedLogo'), 'site-init activates hero gif after first paint');
assert.ok(siteInit.includes('hero-eye-ready'), 'site-init crossfades hero after gif preload');
assert.ok(siteInit.includes('probe.onload'), 'site-init preloads hero gif before reveal');
assert.ok(styles.includes('.hero-logo-wrap.hero-eye-ready .hero-eye-animated'), 'hero animated layer crossfades in with opacity');
assert.ok(styles.includes('.hero-logo-wrap.hero-eye-ready .hero-eye-poster'), 'hero poster fades out during crossfade');
assert.ok(/prefers-reduced-motion:\s*reduce[\s\S]{0,900}\.hero-logo-wrap \.hero-eye-animated/.test(styles), 'reduced motion keeps static poster only');
assert.ok(index.includes('width="250"') && index.includes('height="250"'), 'hero image dimensions stay locked');
assert.ok(stars.includes('STARFIELD_BOOT_DELAY_MS'), 'starfield boot is delayed after first paint');
assert.ok(stars.includes("img.classList.contains('hero-eye-3d')"), 'performance mode keeps hero centerpiece on animated gif');
assert.ok(stars.includes('applyHeroLogoFallback'), 'hero centerpiece can fall back to static png only on load failure');
assert.ok(stars.includes('otp-logo-transparent.png'), 'static png fallback asset remains available');
assert.ok(stars.includes('beginPerformanceProbe'), 'fps probe waits until after initial page load');
assert.ok(stars.includes('PROBE_DELAY_MS'), 'fps probe delay is configurable');
assert.ok(stars.includes('LOW_FPS_SAMPLES_REQUIRED'), 'fps probe requires sustained low fps before activating');
assert.ok(stars.includes('FPS_TRIGGER'), 'fps trigger threshold is configurable');
assert.ok(!stars.includes('if (fps < 45) enablePerformanceMode()'), 'single early fps dip no longer triggers performance mode immediately');
assert.ok(!/enablePerformanceMode\(\)[\s\S]{0,220}applyStaticLogoFallback/.test(stars), 'performance mode does not swap otp brand gifs by default');
assert.ok(stars.includes('applyHeroLogoFallback'), 'hero png fallback remains available on true load failure');
assert.ok(stars.includes("img.classList.contains('hero-eye-3d')"), 'hero centerpiece stays on animated gif during performance mode');
assert.ok(styles.includes('Premium-lite adaptive performance'), 'performance mode css stays premium-lite');
assert.ok(styles.includes('html.stars-performance-mode .home-page .hero .hero-logo-wrap'), 'performance mode keeps hero logo shell polish');
assert.ok(!styles.includes('html.stars-performance-mode .home-page .hero .hero-eye-3d,\nhtml.stars-performance-mode[data-theme="light"] .home-page .hero .hero-eye-3d,\nhtml.stars-performance-mode[data-theme="dark"] .home-page .hero .hero-eye-3d {\n  animation: none !important;\n  transform: none !important;\n  will-change: auto !important;\n  filter: none !important;\n}'), 'performance mode no longer strips all hero logo rendering');
assert.ok(stars.includes('enablePerformanceMode'), 'adaptive starfield performance mode is preserved');
assert.ok(stars.includes('probeAbsoluteStart'), 'adaptive performance detector keeps checking beyond the first sample');
assert.ok(stars.includes("setAttribute('data-otp-performance-mode', 'stars')"), 'starfield activates CSS performance mode selectors');
assert.ok(stars.includes('performanceMode && !mouse.attractor ? 66 : 33'), 'starfield throttles non-interactive redraws in performance mode');
assert.ok(stars.includes('ctx.shadowBlur = performanceMode'), 'starfield softens star glow in performance mode instead of removing it');
assert.ok(!siteInit.includes("data-stars', starsDisabled ? 'disabled' : 'enabled'"), 'remote visuals must not overwrite mounted canvas state with a generic enabled flag');
assert.ok(siteInit.includes("setAttribute('data-stars', 'mounted')"), 'runtime visuals preserve mounted state after config updates');
assert.ok(siteInit.includes('identityMotionProfile'), 'identity card physics use adaptive motion profiles');
assert.ok(siteInit.includes('identityPerformanceLite'), 'identity card reduces motion in performance-lite mode');
assert.ok(siteInit.includes('identityMotionDisabled'), 'identity card disables motion for reduced-motion users');
assert.ok(siteInit.includes("classList.contains('stars-performance-mode')"), 'identity card performance guard follows starfield performance mode');
assert.ok(siteInit.includes('pointermove'), 'identity card listens for pointer movement');
assert.ok(!styles.includes('html.stars-performance-mode .home-page .glass-manifesto {\n  transform: none !important;'), 'performance mode keeps identity card 3D transform');
assert.ok(styles.includes('html.stars-performance-mode .home-page .glass-manifesto {\n  transform: perspective(1200px) rotateX(var(--rotateX, 0deg))'), 'performance mode preserves identity card tilt variables');
assert.ok(styles.includes('.glass-manifesto {\n    transform: perspective(1200px) translate3d(0, 0, 0) !important;'), 'reduced-motion keeps identity card static');

assert.ok(styles.includes('Subpage shell polish: Archive and Insights layout'), 'subpage layout guard is documented');
assert.ok(styles.includes('.insights-page .archive-main'), 'insights uses shared subpage main shell');
assert.ok(styles.includes('padding-top: calc(92px + env(safe-area-inset-top, 0px))'), 'subpage content clears fixed nav');
assert.ok(styles.includes('.archive-page #cursor-canvas.stars-mounted'), 'archive starfield canvas is fixed on subpages');
assert.ok(styles.includes('.archive-page .footer-inner'), 'archive footer spacing is bounded on subpages');
assert.ok(!/\.archive-main\s*\{[^}]*min-height:\s*100vh/.test(styles), 'subpage main does not force viewport dead space');
assert.ok(archive.includes('THE ARCHIVE') && archive.includes('class="archive-main"'), 'archive page exposes visible heading shell');
assert.ok(insights.includes('THE VAULT') && insights.includes('class="archive-main"'), 'insights page exposes visible heading shell');
assert.ok(!insights.includes('padding-top: 140px'), 'insights removes duplicate inline top padding');
assert.ok(styles.includes('font-size: min(1.68rem, 7.1vw) !important;'), 'mobile PERSPECTIVE title sizing guard remains protected');
assert.ok(styles.includes('Premium day-mode services polish: richer depth without changing dark mode.'), 'light-mode services polish remains protected');
assert.ok(stars.includes("img.classList.contains('hero-eye-3d')"), 'animated hero gif performance guard remains protected');
assert.ok(stars.includes('scheduleDrawFrame'), 'starfield schedules frames explicitly');
assert.ok(stars.includes('drawFramePending'), 'starfield avoids duplicate animation frames');
assert.ok(stars.includes("document.visibilityState !== 'visible'"), 'starfield pauses draw loop while tab is hidden');
assert.ok(stars.includes('queueResize'), 'starfield coalesces resize work');
assert.ok(stars.includes('FPS_TRIGGER = 42'), 'fps probe avoids premature performance-mode activation');
assert.ok(stars.includes('LOW_FPS_SAMPLES_REQUIRED = 3'), 'fps probe requires sustained low fps');
assert.ok(siteInit.includes("document.visibilityState !== 'visible'"), 'identity card pauses motion while tab is hidden');
assert.ok(siteInit.includes("visibilitychange"), 'identity card resumes motion when tab becomes visible');
assert.ok(styles.includes('contain: layout style paint'), 'hero uses paint containment without deferred visibility');
assert.ok(!/\.hero\s*\{[^}]*content-visibility:\s*auto/.test(styles), 'hero avoids content-visibility auto jank');
assert.strictEqual((index.match(/styles\.css\?v=([^"'>\s]+)/) || [])[1], '16.8.4', 'homepage styles cache-bust is current');
['archive.html', 'insights.html', 'terms.html', 'privacy.html', '404.html', 'insight.html'].forEach((file) => {
  const html = read(file);
  assert.strictEqual((html.match(/styles\.css\?v=([^"'>\s]+)/) || [])[1], '16.8.4', `${file} styles cache-bust matches index`);
});

console.log('   OK: Homepage visual contract');
console.log('HOMEPAGE VISUAL CONTRACT COMPLETE');
